name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v4

      - name: Check CMake version
        run: cmake --version

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Generate CMake project
        run: cmake -S. -Bbuild -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CONFIGURATION_TYPES=RelWithDebInfo

      - name: Build 64bit release DLL
        run: cmake --build build --config RelWithDebInfo

      - name: Rename DLL to YimLuaAPI-dev-{GITHUB_SHA}.dll
        run: ren YimLuaAPI.dll YimLuaAPI-dev-${{github.sha}}.dll
        working-directory: build/

      - name: Upload Artifact (dll)
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: build/YimLuaAPI-dev-*.dll
      - name: Upload Artifact (pdb)
        uses: actions/upload-artifact@v4
        with:
          name: pdb
          path: build/YimLuaAPI.pdb
